export const SAVE_TOKEN = "SAVE_TOKEN";
export const LOGOUT = "LOGOUT";
// export const FOLLOW_USER = "FOLLOW_USER";
// export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const GET_IMAGES = "GET_IMAGES";
export const LIKE_PHOTO = "LIKE_PHOTO";
export const UNLIKE_PHOTO = "UNLIKE_PHOTO";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const FETCH_USER_LIST = "FETCH_USER_LIST";
